### ISSUE TITLE
주문하기 페이지 이슈1

### ISSUE THREAD

**Issue by limdongjin** [tojung/tojung#31]
1. css 깨짐.=> viewhelper의 경우에 input태그를 div로 묶어서 렌더링 하기때문에 기존 order/ 폴더의 css와는 달라지는것으로 보임. + form 태그 여러개 있는거 지우고 form_tag로 변경하면서 해당 폼태그에 있는 class들이 날아가면서 발생하는것도 요인중 하나로 예상됨

2. 법안 상품 메인 이미지 크기 고정 안됨. 메인이미지가 매우 클경우 가격 부분이 가려지는 경우 발생 

3. 데스크탑버전에서 textarea 작게됨. 화면 크기에 따라 cols rows 크기 다르게 해야할듯.

4. order/ 폴더의 주문페이지는 일반 텍스트로 가격 나타냈는데, 요구사항이 가격수정할수있어야해서 가격 수정 할수있는 input태그 추가했음. +  제플린에는 "더 많은 후원을 하고 싶다면 금액을 수정해주세요. " 멘트도 있어서 이거도 추가했음 => css 화이팅...

5. 주문 금액 부분( 제플린 기준 총상품금액, 국회청원 몇건, 배송비 네모 박스 세개 있는 부분)의 네모박스 경계선이 안보임. (음 로컬에서 할때 잘됬었다면 1번 이슈로 인한 문제일수도)

6. input 태그 특성상 인풋 네모박스의 경계선이 뚜렷하게 보이게됨. 그러나.. 제플린의 주문 고객 정보 적는 부분은 경계선이 없슴.. (음 로컬에서 할때 잘됬었다면 1번 이슈로 인한 문제일수도)

**Comment by limdongjin** [comment]
뷰헬퍼의 ~field_tag는 결국 input으로 렌더링 되니까 어쩔수없다면 html input태그로 구현해도 될것으로 보임. <%= form_tag ~ %> 부분정도만 뷰헬퍼로 구현하면 될듯.

**Comment by limdongjin** [comment]
고칠때 javascript 함수 주의 주의. id값으로 get element하는 코드 맨밑에 있음.

**Comment by Zinyon** [comment]
모두 완료
