### ISSUE TITLE
법안 상품 상세페이지 관련이슈3

### ISSUE THREAD

**Issue by limdongjin** [tojung/tojung#32]
모바일의 경우.

패키지를 선택 및 클릭 -> 내인생으로 배달받기 클릭 -> bottom bar 위에 부분이 fade됨 -> 내인생으로 배달 받기 클릭 -> 주문 페이지로 이동함. 

즉 내인생으로 배달받기를 두번 클릭해야 주문페이지로 이동됨.

**Comment by Zinyon** [comment]
package img 클릭 했을 때 a tag href 생기도록 수정
